// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0-devel
// 	protoc        v3.15.8
// source: pay_ment_api.proto

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Order struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OrderNum  string `protobuf:"bytes,1,opt,name=OrderNum,proto3" json:"OrderNum,omitempty"`
	OrderTyp  string `protobuf:"bytes,2,opt,name=OrderTyp,proto3" json:"OrderTyp,omitempty"`
	OrderInfo []byte `protobuf:"bytes,3,opt,name=OrderInfo,proto3" json:"OrderInfo,omitempty"`
}

func (x *Order) Reset() {
	*x = Order{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pay_ment_api_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Order) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Order) ProtoMessage() {}

func (x *Order) ProtoReflect() protoreflect.Message {
	mi := &file_pay_ment_api_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Order.ProtoReflect.Descriptor instead.
func (*Order) Descriptor() ([]byte, []int) {
	return file_pay_ment_api_proto_rawDescGZIP(), []int{0}
}

func (x *Order) GetOrderNum() string {
	if x != nil {
		return x.OrderNum
	}
	return ""
}

func (x *Order) GetOrderTyp() string {
	if x != nil {
		return x.OrderTyp
	}
	return ""
}

func (x *Order) GetOrderInfo() []byte {
	if x != nil {
		return x.OrderInfo
	}
	return nil
}

// TX type of OrderInfo
type TxOrder struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FromTyp string `protobuf:"bytes,1,opt,name=FromTyp,proto3" json:"FromTyp,omitempty"`
	ToTyp   string `protobuf:"bytes,2,opt,name=ToTyp,proto3" json:"ToTyp,omitempty"`
	From    string `protobuf:"bytes,3,opt,name=From,proto3" json:"From,omitempty"`
	To      string `protobuf:"bytes,4,opt,name=To,proto3" json:"To,omitempty"`
	Amount  int64  `protobuf:"varint,5,opt,name=Amount,proto3" json:"Amount,omitempty"`
}

func (x *TxOrder) Reset() {
	*x = TxOrder{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pay_ment_api_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TxOrder) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxOrder) ProtoMessage() {}

func (x *TxOrder) ProtoReflect() protoreflect.Message {
	mi := &file_pay_ment_api_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxOrder.ProtoReflect.Descriptor instead.
func (*TxOrder) Descriptor() ([]byte, []int) {
	return file_pay_ment_api_proto_rawDescGZIP(), []int{1}
}

func (x *TxOrder) GetFromTyp() string {
	if x != nil {
		return x.FromTyp
	}
	return ""
}

func (x *TxOrder) GetToTyp() string {
	if x != nil {
		return x.ToTyp
	}
	return ""
}

func (x *TxOrder) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *TxOrder) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *TxOrder) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

//// CON type of OrderInfo
type ContractOrder struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FromTyp string `protobuf:"bytes,1,opt,name=FromTyp,proto3" json:"FromTyp,omitempty"`
	ToTyp   string `protobuf:"bytes,2,opt,name=ToTyp,proto3" json:"ToTyp,omitempty"`
	From    string `protobuf:"bytes,3,opt,name=From,proto3" json:"From,omitempty"`
	To      string `protobuf:"bytes,4,opt,name=To,proto3" json:"To,omitempty"`
	Payload []byte `protobuf:"bytes,5,opt,name=Payload,proto3" json:"Payload,omitempty"`
}

func (x *ContractOrder) Reset() {
	*x = ContractOrder{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pay_ment_api_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ContractOrder) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContractOrder) ProtoMessage() {}

func (x *ContractOrder) ProtoReflect() protoreflect.Message {
	mi := &file_pay_ment_api_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContractOrder.ProtoReflect.Descriptor instead.
func (*ContractOrder) Descriptor() ([]byte, []int) {
	return file_pay_ment_api_proto_rawDescGZIP(), []int{2}
}

func (x *ContractOrder) GetFromTyp() string {
	if x != nil {
		return x.FromTyp
	}
	return ""
}

func (x *ContractOrder) GetToTyp() string {
	if x != nil {
		return x.ToTyp
	}
	return ""
}

func (x *ContractOrder) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *ContractOrder) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *ContractOrder) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

// general response
type GeneralResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool   `protobuf:"varint,1,opt,name=Success,proto3" json:"Success,omitempty"`
	Data    []byte `protobuf:"bytes,2,opt,name=Data,proto3" json:"Data,omitempty"`
}

func (x *GeneralResp) Reset() {
	*x = GeneralResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pay_ment_api_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GeneralResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeneralResp) ProtoMessage() {}

func (x *GeneralResp) ProtoReflect() protoreflect.Message {
	mi := &file_pay_ment_api_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeneralResp.ProtoReflect.Descriptor instead.
func (*GeneralResp) Descriptor() ([]byte, []int) {
	return file_pay_ment_api_proto_rawDescGZIP(), []int{3}
}

func (x *GeneralResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GeneralResp) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// generate ADDR
type GenAddrReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Typ string `protobuf:"bytes,1,opt,name=Typ,proto3" json:"Typ,omitempty"`
}

func (x *GenAddrReq) Reset() {
	*x = GenAddrReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pay_ment_api_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GenAddrReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenAddrReq) ProtoMessage() {}

func (x *GenAddrReq) ProtoReflect() protoreflect.Message {
	mi := &file_pay_ment_api_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenAddrReq.ProtoReflect.Descriptor instead.
func (*GenAddrReq) Descriptor() ([]byte, []int) {
	return file_pay_ment_api_proto_rawDescGZIP(), []int{4}
}

func (x *GenAddrReq) GetTyp() string {
	if x != nil {
		return x.Typ
	}
	return ""
}

// withdraw request
type WithdrawReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Typ           string `protobuf:"bytes,1,opt,name=Typ,proto3" json:"Typ,omitempty"`
	Amount        int64  `protobuf:"varint,2,opt,name=Amount,proto3" json:"Amount,omitempty"`
	TargetAddress string `protobuf:"bytes,3,opt,name=TargetAddress,proto3" json:"TargetAddress,omitempty"`
	CallbackURL   string `protobuf:"bytes,4,opt,name=CallbackURL,proto3" json:"CallbackURL,omitempty"`
}

func (x *WithdrawReq) Reset() {
	*x = WithdrawReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pay_ment_api_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WithdrawReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WithdrawReq) ProtoMessage() {}

func (x *WithdrawReq) ProtoReflect() protoreflect.Message {
	mi := &file_pay_ment_api_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WithdrawReq.ProtoReflect.Descriptor instead.
func (*WithdrawReq) Descriptor() ([]byte, []int) {
	return file_pay_ment_api_proto_rawDescGZIP(), []int{5}
}

func (x *WithdrawReq) GetTyp() string {
	if x != nil {
		return x.Typ
	}
	return ""
}

func (x *WithdrawReq) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *WithdrawReq) GetTargetAddress() string {
	if x != nil {
		return x.TargetAddress
	}
	return ""
}

func (x *WithdrawReq) GetCallbackURL() string {
	if x != nil {
		return x.CallbackURL
	}
	return ""
}

// transfer request
type TransferReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TargetTyp   string `protobuf:"bytes,1,opt,name=TargetTyp,proto3" json:"TargetTyp,omitempty"`
	TargetData  string `protobuf:"bytes,2,opt,name=TargetData,proto3" json:"TargetData,omitempty"`
	Amount      int64  `protobuf:"varint,3,opt,name=Amount,proto3" json:"Amount,omitempty"`
	Typ         string `protobuf:"bytes,4,opt,name=Typ,proto3" json:"Typ,omitempty"`
	CallbackURL string `protobuf:"bytes,5,opt,name=CallbackURL,proto3" json:"CallbackURL,omitempty"`
}

func (x *TransferReq) Reset() {
	*x = TransferReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pay_ment_api_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TransferReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferReq) ProtoMessage() {}

func (x *TransferReq) ProtoReflect() protoreflect.Message {
	mi := &file_pay_ment_api_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferReq.ProtoReflect.Descriptor instead.
func (*TransferReq) Descriptor() ([]byte, []int) {
	return file_pay_ment_api_proto_rawDescGZIP(), []int{6}
}

func (x *TransferReq) GetTargetTyp() string {
	if x != nil {
		return x.TargetTyp
	}
	return ""
}

func (x *TransferReq) GetTargetData() string {
	if x != nil {
		return x.TargetData
	}
	return ""
}

func (x *TransferReq) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *TransferReq) GetTyp() string {
	if x != nil {
		return x.Typ
	}
	return ""
}

func (x *TransferReq) GetCallbackURL() string {
	if x != nil {
		return x.CallbackURL
	}
	return ""
}

// find order request
type FindOrderReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OrderNum string `protobuf:"bytes,1,opt,name=OrderNum,proto3" json:"OrderNum,omitempty"`
}

func (x *FindOrderReq) Reset() {
	*x = FindOrderReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pay_ment_api_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindOrderReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindOrderReq) ProtoMessage() {}

func (x *FindOrderReq) ProtoReflect() protoreflect.Message {
	mi := &file_pay_ment_api_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindOrderReq.ProtoReflect.Descriptor instead.
func (*FindOrderReq) Descriptor() ([]byte, []int) {
	return file_pay_ment_api_proto_rawDescGZIP(), []int{7}
}

func (x *FindOrderReq) GetOrderNum() string {
	if x != nil {
		return x.OrderNum
	}
	return ""
}

// call contract request
type CallContractReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Payload []byte `protobuf:"bytes,1,opt,name=Payload,proto3" json:"Payload,omitempty"`
	Typ     string `protobuf:"bytes,2,opt,name=Typ,proto3" json:"Typ,omitempty"`
}

func (x *CallContractReq) Reset() {
	*x = CallContractReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pay_ment_api_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CallContractReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallContractReq) ProtoMessage() {}

func (x *CallContractReq) ProtoReflect() protoreflect.Message {
	mi := &file_pay_ment_api_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallContractReq.ProtoReflect.Descriptor instead.
func (*CallContractReq) Descriptor() ([]byte, []int) {
	return file_pay_ment_api_proto_rawDescGZIP(), []int{8}
}

func (x *CallContractReq) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *CallContractReq) GetTyp() string {
	if x != nil {
		return x.Typ
	}
	return ""
}

// response for generate address
type GenAddrResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Address string `protobuf:"bytes,1,opt,name=Address,proto3" json:"Address,omitempty"`
	Typ     string `protobuf:"bytes,2,opt,name=Typ,proto3" json:"Typ,omitempty"`
}

func (x *GenAddrResp) Reset() {
	*x = GenAddrResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pay_ment_api_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GenAddrResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenAddrResp) ProtoMessage() {}

func (x *GenAddrResp) ProtoReflect() protoreflect.Message {
	mi := &file_pay_ment_api_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenAddrResp.ProtoReflect.Descriptor instead.
func (*GenAddrResp) Descriptor() ([]byte, []int) {
	return file_pay_ment_api_proto_rawDescGZIP(), []int{9}
}

func (x *GenAddrResp) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *GenAddrResp) GetTyp() string {
	if x != nil {
		return x.Typ
	}
	return ""
}

// response for withdraw
type WithdrawResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OrderNum string `protobuf:"bytes,1,opt,name=OrderNum,proto3" json:"OrderNum,omitempty"`
}

func (x *WithdrawResp) Reset() {
	*x = WithdrawResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pay_ment_api_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WithdrawResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WithdrawResp) ProtoMessage() {}

func (x *WithdrawResp) ProtoReflect() protoreflect.Message {
	mi := &file_pay_ment_api_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WithdrawResp.ProtoReflect.Descriptor instead.
func (*WithdrawResp) Descriptor() ([]byte, []int) {
	return file_pay_ment_api_proto_rawDescGZIP(), []int{10}
}

func (x *WithdrawResp) GetOrderNum() string {
	if x != nil {
		return x.OrderNum
	}
	return ""
}

// response for transfer
type TransferResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OrderNum string `protobuf:"bytes,1,opt,name=OrderNum,proto3" json:"OrderNum,omitempty"`
}

func (x *TransferResp) Reset() {
	*x = TransferResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pay_ment_api_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TransferResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferResp) ProtoMessage() {}

func (x *TransferResp) ProtoReflect() protoreflect.Message {
	mi := &file_pay_ment_api_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferResp.ProtoReflect.Descriptor instead.
func (*TransferResp) Descriptor() ([]byte, []int) {
	return file_pay_ment_api_proto_rawDescGZIP(), []int{11}
}

func (x *TransferResp) GetOrderNum() string {
	if x != nil {
		return x.OrderNum
	}
	return ""
}

// response for find order
type FindOrderResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Order *Order `protobuf:"bytes,1,opt,name=Order,proto3" json:"Order,omitempty"`
}

func (x *FindOrderResp) Reset() {
	*x = FindOrderResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pay_ment_api_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindOrderResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindOrderResp) ProtoMessage() {}

func (x *FindOrderResp) ProtoReflect() protoreflect.Message {
	mi := &file_pay_ment_api_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindOrderResp.ProtoReflect.Descriptor instead.
func (*FindOrderResp) Descriptor() ([]byte, []int) {
	return file_pay_ment_api_proto_rawDescGZIP(), []int{12}
}

func (x *FindOrderResp) GetOrder() *Order {
	if x != nil {
		return x.Order
	}
	return nil
}

// response for call contract
type CallContractResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Payload []byte `protobuf:"bytes,1,opt,name=Payload,proto3" json:"Payload,omitempty"`
}

func (x *CallContractResp) Reset() {
	*x = CallContractResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pay_ment_api_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CallContractResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallContractResp) ProtoMessage() {}

func (x *CallContractResp) ProtoReflect() protoreflect.Message {
	mi := &file_pay_ment_api_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallContractResp.ProtoReflect.Descriptor instead.
func (*CallContractResp) Descriptor() ([]byte, []int) {
	return file_pay_ment_api_proto_rawDescGZIP(), []int{13}
}

func (x *CallContractResp) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

var File_pay_ment_api_proto protoreflect.FileDescriptor

var file_pay_ment_api_proto_rawDesc = []byte{
	0x0a, 0x12, 0x70, 0x61, 0x79, 0x5f, 0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x61, 0x70, 0x69, 0x22, 0x5d, 0x0a, 0x05, 0x4f, 0x72, 0x64,
	0x65, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x4e, 0x75, 0x6d, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x4e, 0x75, 0x6d, 0x12, 0x1a,
	0x0a, 0x08, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x54, 0x79, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x54, 0x79, 0x70, 0x12, 0x1c, 0x0a, 0x09, 0x4f, 0x72,
	0x64, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x4f,
	0x72, 0x64, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x75, 0x0a, 0x07, 0x54, 0x78, 0x4f, 0x72,
	0x64, 0x65, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x46, 0x72, 0x6f, 0x6d, 0x54, 0x79, 0x70, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x46, 0x72, 0x6f, 0x6d, 0x54, 0x79, 0x70, 0x12, 0x14, 0x0a,
	0x05, 0x54, 0x6f, 0x54, 0x79, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x54, 0x6f,
	0x54, 0x79, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x46, 0x72, 0x6f, 0x6d, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x46, 0x72, 0x6f, 0x6d, 0x12, 0x0e, 0x0a, 0x02, 0x54, 0x6f, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x54, 0x6f, 0x12, 0x16, 0x0a, 0x06, 0x41, 0x6d, 0x6f, 0x75, 0x6e,
	0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x22,
	0x7d, 0x0a, 0x0d, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x4f, 0x72, 0x64, 0x65, 0x72,
	0x12, 0x18, 0x0a, 0x07, 0x46, 0x72, 0x6f, 0x6d, 0x54, 0x79, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x46, 0x72, 0x6f, 0x6d, 0x54, 0x79, 0x70, 0x12, 0x14, 0x0a, 0x05, 0x54, 0x6f,
	0x54, 0x79, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x54, 0x6f, 0x54, 0x79, 0x70,
	0x12, 0x12, 0x0a, 0x04, 0x46, 0x72, 0x6f, 0x6d, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x46, 0x72, 0x6f, 0x6d, 0x12, 0x0e, 0x0a, 0x02, 0x54, 0x6f, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x54, 0x6f, 0x12, 0x18, 0x0a, 0x07, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x22, 0x3b,
	0x0a, 0x0b, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x12, 0x18, 0x0a,
	0x07, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07,
	0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x44, 0x61, 0x74, 0x61, 0x22, 0x1e, 0x0a, 0x0a, 0x47,
	0x65, 0x6e, 0x41, 0x64, 0x64, 0x72, 0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x54, 0x79, 0x70,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x54, 0x79, 0x70, 0x22, 0x7f, 0x0a, 0x0b, 0x57,
	0x69, 0x74, 0x68, 0x64, 0x72, 0x61, 0x77, 0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x54, 0x79,
	0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x54, 0x79, 0x70, 0x12, 0x16, 0x0a, 0x06,
	0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x41, 0x6d,
	0x6f, 0x75, 0x6e, 0x74, 0x12, 0x24, 0x0a, 0x0d, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x41, 0x64,
	0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x54, 0x61, 0x72,
	0x67, 0x65, 0x74, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x20, 0x0a, 0x0b, 0x43, 0x61,
	0x6c, 0x6c, 0x62, 0x61, 0x63, 0x6b, 0x55, 0x52, 0x4c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0b, 0x43, 0x61, 0x6c, 0x6c, 0x62, 0x61, 0x63, 0x6b, 0x55, 0x52, 0x4c, 0x22, 0x97, 0x01, 0x0a,
	0x0b, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x52, 0x65, 0x71, 0x12, 0x1c, 0x0a, 0x09,
	0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x54, 0x79, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x54, 0x79, 0x70, 0x12, 0x1e, 0x0a, 0x0a, 0x54, 0x61,
	0x72, 0x67, 0x65, 0x74, 0x44, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a,
	0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x44, 0x61, 0x74, 0x61, 0x12, 0x16, 0x0a, 0x06, 0x41, 0x6d,
	0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x41, 0x6d, 0x6f, 0x75,
	0x6e, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x54, 0x79, 0x70, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x54, 0x79, 0x70, 0x12, 0x20, 0x0a, 0x0b, 0x43, 0x61, 0x6c, 0x6c, 0x62, 0x61, 0x63, 0x6b,
	0x55, 0x52, 0x4c, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x43, 0x61, 0x6c, 0x6c, 0x62,
	0x61, 0x63, 0x6b, 0x55, 0x52, 0x4c, 0x22, 0x2a, 0x0a, 0x0c, 0x46, 0x69, 0x6e, 0x64, 0x4f, 0x72,
	0x64, 0x65, 0x72, 0x52, 0x65, 0x71, 0x12, 0x1a, 0x0a, 0x08, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x4e,
	0x75, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x4e,
	0x75, 0x6d, 0x22, 0x3d, 0x0a, 0x0f, 0x43, 0x61, 0x6c, 0x6c, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x61,
	0x63, 0x74, 0x52, 0x65, 0x71, 0x12, 0x18, 0x0a, 0x07, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x12,
	0x10, 0x0a, 0x03, 0x54, 0x79, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x54, 0x79,
	0x70, 0x22, 0x39, 0x0a, 0x0b, 0x47, 0x65, 0x6e, 0x41, 0x64, 0x64, 0x72, 0x52, 0x65, 0x73, 0x70,
	0x12, 0x18, 0x0a, 0x07, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x54, 0x79,
	0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x54, 0x79, 0x70, 0x22, 0x2a, 0x0a, 0x0c,
	0x57, 0x69, 0x74, 0x68, 0x64, 0x72, 0x61, 0x77, 0x52, 0x65, 0x73, 0x70, 0x12, 0x1a, 0x0a, 0x08,
	0x4f, 0x72, 0x64, 0x65, 0x72, 0x4e, 0x75, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x4f, 0x72, 0x64, 0x65, 0x72, 0x4e, 0x75, 0x6d, 0x22, 0x2a, 0x0a, 0x0c, 0x54, 0x72, 0x61, 0x6e,
	0x73, 0x66, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x12, 0x1a, 0x0a, 0x08, 0x4f, 0x72, 0x64, 0x65,
	0x72, 0x4e, 0x75, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x4f, 0x72, 0x64, 0x65,
	0x72, 0x4e, 0x75, 0x6d, 0x22, 0x31, 0x0a, 0x0d, 0x46, 0x69, 0x6e, 0x64, 0x4f, 0x72, 0x64, 0x65,
	0x72, 0x52, 0x65, 0x73, 0x70, 0x12, 0x20, 0x0a, 0x05, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x4f, 0x72, 0x64, 0x65, 0x72,
	0x52, 0x05, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x22, 0x2c, 0x0a, 0x10, 0x43, 0x61, 0x6c, 0x6c, 0x43,
	0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x18, 0x0a, 0x07, 0x50,
	0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x50, 0x61,
	0x79, 0x6c, 0x6f, 0x61, 0x64, 0x32, 0x94, 0x02, 0x0a, 0x06, 0x50, 0x61, 0x79, 0x41, 0x70, 0x69,
	0x12, 0x31, 0x0a, 0x08, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x12, 0x10, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x52, 0x65, 0x71, 0x1a, 0x11,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x52, 0x65, 0x73,
	0x70, 0x22, 0x00, 0x12, 0x34, 0x0a, 0x09, 0x46, 0x69, 0x6e, 0x64, 0x4f, 0x72, 0x64, 0x65, 0x72,
	0x12, 0x11, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x46, 0x69, 0x6e, 0x64, 0x4f, 0x72, 0x64, 0x65, 0x72,
	0x52, 0x65, 0x71, 0x1a, 0x12, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x46, 0x69, 0x6e, 0x64, 0x4f, 0x72,
	0x64, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x12, 0x31, 0x0a, 0x08, 0x57, 0x69, 0x74,
	0x68, 0x64, 0x72, 0x61, 0x77, 0x12, 0x10, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x57, 0x69, 0x74, 0x68,
	0x64, 0x72, 0x61, 0x77, 0x52, 0x65, 0x71, 0x1a, 0x11, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x57, 0x69,
	0x74, 0x68, 0x64, 0x72, 0x61, 0x77, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x12, 0x2f, 0x0a, 0x08,
	0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x12, 0x0f, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x47,
	0x65, 0x6e, 0x41, 0x64, 0x64, 0x72, 0x52, 0x65, 0x71, 0x1a, 0x10, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x47, 0x65, 0x6e, 0x41, 0x64, 0x64, 0x72, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x12, 0x3d, 0x0a,
	0x0c, 0x43, 0x61, 0x6c, 0x6c, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x12, 0x14, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x43, 0x61, 0x6c, 0x6c, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74,
	0x52, 0x65, 0x71, 0x1a, 0x15, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x43, 0x61, 0x6c, 0x6c, 0x43, 0x6f,
	0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x42, 0x04, 0x5a, 0x02,
	0x2e, 0x2f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pay_ment_api_proto_rawDescOnce sync.Once
	file_pay_ment_api_proto_rawDescData = file_pay_ment_api_proto_rawDesc
)

func file_pay_ment_api_proto_rawDescGZIP() []byte {
	file_pay_ment_api_proto_rawDescOnce.Do(func() {
		file_pay_ment_api_proto_rawDescData = protoimpl.X.CompressGZIP(file_pay_ment_api_proto_rawDescData)
	})
	return file_pay_ment_api_proto_rawDescData
}

var file_pay_ment_api_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_pay_ment_api_proto_goTypes = []interface{}{
	(*Order)(nil),            // 0: api.Order
	(*TxOrder)(nil),          // 1: api.TxOrder
	(*ContractOrder)(nil),    // 2: api.ContractOrder
	(*GeneralResp)(nil),      // 3: api.GeneralResp
	(*GenAddrReq)(nil),       // 4: api.GenAddrReq
	(*WithdrawReq)(nil),      // 5: api.WithdrawReq
	(*TransferReq)(nil),      // 6: api.TransferReq
	(*FindOrderReq)(nil),     // 7: api.FindOrderReq
	(*CallContractReq)(nil),  // 8: api.CallContractReq
	(*GenAddrResp)(nil),      // 9: api.GenAddrResp
	(*WithdrawResp)(nil),     // 10: api.WithdrawResp
	(*TransferResp)(nil),     // 11: api.TransferResp
	(*FindOrderResp)(nil),    // 12: api.FindOrderResp
	(*CallContractResp)(nil), // 13: api.CallContractResp
}
var file_pay_ment_api_proto_depIdxs = []int32{
	0,  // 0: api.FindOrderResp.Order:type_name -> api.Order
	6,  // 1: api.PayApi.Transfer:input_type -> api.TransferReq
	7,  // 2: api.PayApi.FindOrder:input_type -> api.FindOrderReq
	5,  // 3: api.PayApi.Withdraw:input_type -> api.WithdrawReq
	4,  // 4: api.PayApi.Generate:input_type -> api.GenAddrReq
	8,  // 5: api.PayApi.CallContract:input_type -> api.CallContractReq
	11, // 6: api.PayApi.Transfer:output_type -> api.TransferResp
	12, // 7: api.PayApi.FindOrder:output_type -> api.FindOrderResp
	10, // 8: api.PayApi.Withdraw:output_type -> api.WithdrawResp
	9,  // 9: api.PayApi.Generate:output_type -> api.GenAddrResp
	13, // 10: api.PayApi.CallContract:output_type -> api.CallContractResp
	6,  // [6:11] is the sub-list for method output_type
	1,  // [1:6] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_pay_ment_api_proto_init() }
func file_pay_ment_api_proto_init() {
	if File_pay_ment_api_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pay_ment_api_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Order); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pay_ment_api_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TxOrder); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pay_ment_api_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ContractOrder); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pay_ment_api_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GeneralResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pay_ment_api_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GenAddrReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pay_ment_api_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WithdrawReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pay_ment_api_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TransferReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pay_ment_api_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindOrderReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pay_ment_api_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CallContractReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pay_ment_api_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GenAddrResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pay_ment_api_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WithdrawResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pay_ment_api_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TransferResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pay_ment_api_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindOrderResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pay_ment_api_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CallContractResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pay_ment_api_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pay_ment_api_proto_goTypes,
		DependencyIndexes: file_pay_ment_api_proto_depIdxs,
		MessageInfos:      file_pay_ment_api_proto_msgTypes,
	}.Build()
	File_pay_ment_api_proto = out.File
	file_pay_ment_api_proto_rawDesc = nil
	file_pay_ment_api_proto_goTypes = nil
	file_pay_ment_api_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// PayApiClient is the client API for PayApi service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PayApiClient interface {
	Transfer(ctx context.Context, in *TransferReq, opts ...grpc.CallOption) (*TransferResp, error)
	FindOrder(ctx context.Context, in *FindOrderReq, opts ...grpc.CallOption) (*FindOrderResp, error)
	Withdraw(ctx context.Context, in *WithdrawReq, opts ...grpc.CallOption) (*WithdrawResp, error)
	Generate(ctx context.Context, in *GenAddrReq, opts ...grpc.CallOption) (*GenAddrResp, error)
	CallContract(ctx context.Context, in *CallContractReq, opts ...grpc.CallOption) (*CallContractResp, error)
}

type payApiClient struct {
	cc grpc.ClientConnInterface
}

func NewPayApiClient(cc grpc.ClientConnInterface) PayApiClient {
	return &payApiClient{cc}
}

func (c *payApiClient) Transfer(ctx context.Context, in *TransferReq, opts ...grpc.CallOption) (*TransferResp, error) {
	out := new(TransferResp)
	err := c.cc.Invoke(ctx, "/api.PayApi/Transfer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *payApiClient) FindOrder(ctx context.Context, in *FindOrderReq, opts ...grpc.CallOption) (*FindOrderResp, error) {
	out := new(FindOrderResp)
	err := c.cc.Invoke(ctx, "/api.PayApi/FindOrder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *payApiClient) Withdraw(ctx context.Context, in *WithdrawReq, opts ...grpc.CallOption) (*WithdrawResp, error) {
	out := new(WithdrawResp)
	err := c.cc.Invoke(ctx, "/api.PayApi/Withdraw", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *payApiClient) Generate(ctx context.Context, in *GenAddrReq, opts ...grpc.CallOption) (*GenAddrResp, error) {
	out := new(GenAddrResp)
	err := c.cc.Invoke(ctx, "/api.PayApi/Generate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *payApiClient) CallContract(ctx context.Context, in *CallContractReq, opts ...grpc.CallOption) (*CallContractResp, error) {
	out := new(CallContractResp)
	err := c.cc.Invoke(ctx, "/api.PayApi/CallContract", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PayApiServer is the server API for PayApi service.
type PayApiServer interface {
	Transfer(context.Context, *TransferReq) (*TransferResp, error)
	FindOrder(context.Context, *FindOrderReq) (*FindOrderResp, error)
	Withdraw(context.Context, *WithdrawReq) (*WithdrawResp, error)
	Generate(context.Context, *GenAddrReq) (*GenAddrResp, error)
	CallContract(context.Context, *CallContractReq) (*CallContractResp, error)
}

// UnimplementedPayApiServer can be embedded to have forward compatible implementations.
type UnimplementedPayApiServer struct {
}

func (*UnimplementedPayApiServer) Transfer(context.Context, *TransferReq) (*TransferResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Transfer not implemented")
}
func (*UnimplementedPayApiServer) FindOrder(context.Context, *FindOrderReq) (*FindOrderResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindOrder not implemented")
}
func (*UnimplementedPayApiServer) Withdraw(context.Context, *WithdrawReq) (*WithdrawResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Withdraw not implemented")
}
func (*UnimplementedPayApiServer) Generate(context.Context, *GenAddrReq) (*GenAddrResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Generate not implemented")
}
func (*UnimplementedPayApiServer) CallContract(context.Context, *CallContractReq) (*CallContractResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CallContract not implemented")
}

func RegisterPayApiServer(s *grpc.Server, srv PayApiServer) {
	s.RegisterService(&_PayApi_serviceDesc, srv)
}

func _PayApi_Transfer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransferReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PayApiServer).Transfer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.PayApi/Transfer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PayApiServer).Transfer(ctx, req.(*TransferReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _PayApi_FindOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindOrderReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PayApiServer).FindOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.PayApi/FindOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PayApiServer).FindOrder(ctx, req.(*FindOrderReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _PayApi_Withdraw_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WithdrawReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PayApiServer).Withdraw(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.PayApi/Withdraw",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PayApiServer).Withdraw(ctx, req.(*WithdrawReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _PayApi_Generate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenAddrReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PayApiServer).Generate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.PayApi/Generate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PayApiServer).Generate(ctx, req.(*GenAddrReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _PayApi_CallContract_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CallContractReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PayApiServer).CallContract(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.PayApi/CallContract",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PayApiServer).CallContract(ctx, req.(*CallContractReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _PayApi_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.PayApi",
	HandlerType: (*PayApiServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Transfer",
			Handler:    _PayApi_Transfer_Handler,
		},
		{
			MethodName: "FindOrder",
			Handler:    _PayApi_FindOrder_Handler,
		},
		{
			MethodName: "Withdraw",
			Handler:    _PayApi_Withdraw_Handler,
		},
		{
			MethodName: "Generate",
			Handler:    _PayApi_Generate_Handler,
		},
		{
			MethodName: "CallContract",
			Handler:    _PayApi_CallContract_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pay_ment_api.proto",
}
